### ISSUE TITLE
Ssh agent forwarding for ssh key pair authentication

### ISSUE THREAD

**Issue by kevy1234** [ybulach/pysshrp#1]
Does pyssrp support SSH agent forwarding? I would like to install the SSH private keys on the downstream client, instead of leaving keys sitting on the reverse proxy server. Is it possible?

**Comment by ybulach** [comment]
You can keep your private keys on the downstream(s) without the need of leaving this keys of the pysshrp server, but without implementing agent forwarding.

You will need an `upstream_key` (in upstreams configuration) on the pysshrp server, that will be used to look for the downstream key on the upstream:
- Client connects providing his public key
- Pysshrp connects to the upstream with his `upstream_key`
- Pysshrp looks for the client public key on the upstream's `authorized_keys`
- Pysshrp connects the client to the upstream (actually, the SSH connection will still come from Pysshrp)

So the public part of `upstream_key` must also be added in the upstream's `authorized_keys` for the lookup to work properly. It is most likely a `/etc/pysshrp/client.key` that can be used for all upstreams, but can be different keys. It is not recommanded to use the existing server.key used for incoming connections.

The upstream will handle all clients public keys, private keys still on the client/downstream.

Does this answer your question ?

**Comment by kevy1234** [comment]
This is what I did:

On the pysshrp server I ran command to generate the key pair
#ssh-keygen -f /etc/pysshrp/client.key

in /etc/pysshrp/config.py, I set:
'upstream_key': '/etc/pysshrp/client.key',

I copied the public key client.key.pub to the upstream and appended it to the authorized_keys file, and it failed with the following output, what did I miss? If I bypass pysshrp then the downstream is able to connect to upsteram without typing password.

pysshrp INFO - *************************************************
pysshrp INFO - Loading configuration
pysshrp INFO - Configuration loaded successfully
pysshrp INFO - Starting pysshrpd server thread on 0.0.0.0:2200
pysshrpd.server INFO - New client thread started from 10.0.2.2:53746
pysshrpd.client INFO - 10.0.2.2:53746: trying publickey authentication for "test1"
pysshrpd.client INFO - 10.0.2.2:53746: connected to upstream test1@10.21.2.50:5022
pysshrpd.client CRITICAL - 10.0.2.2:53746: authentication of "test1" with publickey failed
pysshrpd.client INFO - 10.0.2.2:53746: trying password authentication for "test1"
pysshrpd.client INFO - 10.0.2.2:53746: connected to upstream test1@10.21.2.50:5022
pysshrpd.client INFO - 10.0.2.2:53746: new subsystem "sftp" requested

**Comment by ybulach** [comment]
This line indicates that the upstream connection is successful with the provided `upstream_key`:

```
pysshrpd.client INFO - 10.0.2.2:53746: connected to upstream test1@10.21.2.50:5022
```

Is your downstream (client: 10.0.2.2) public key also in the upstream (10.21.2.50) `authorized_keys` file ?

**Comment by kevy1234** [comment]
Yes, the downstream public key is added, the client 10.0.2.2 is able to connect to 10.21.2.50:5022 directly without password.

**Comment by ybulach** [comment]
Sounds like a failure when trying to check .ssh/authorized_keys.

Can you try with the last commit, changing the log level to debug in configuration (this will be quite verbose) ?

```
level = 'DEBUG'
```

**Comment by kevy1234** [comment]
Enabled debugging mode

pysshrp INFO - *************************************************
pysshrp INFO - Loading configuration
pysshrp INFO - Configuration loaded successfully
pysshrp INFO - Starting pysshrpd server thread on 0.0.0.0:2200
pysshrpd.server INFO - New client thread started from 10.0.2.2:56011
paramiko.transport DEBUG - starting thread (server mode): 0x296ad50L
paramiko.transport INFO - Connected (version 2.0, client WinSCP_release_5.7)
paramiko.transport DEBUG - kex algos:['diffie-hellman-group-exchange-sha256', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1', 'rsa2048-sha256', 'rsa1024-sha1'] server key:['ssh-rsa', 'ssh-dss'] client encrypt:['aes256-ctr', 'aes256-cbc', 'rijndael-cbc@lysator.liu.se', 'aes192-ctr', 'aes192-cbc', 'aes128-ctr', 'aes128-cbc', 'blowfish-ctr', 'blowfish-cbc', '3des-ctr', '3des-cbc', 'arcfour256', 'arcfour128'] server encrypt:['aes256-ctr', 'aes256-cbc', 'rijndael-cbc@lysator.liu.se', 'aes192-ctr', 'aes192-cbc', 'aes128-ctr', 'aes128-cbc', 'blowfish-ctr', 'blowfish-cbc', '3des-ctr', '3des-cbc', 'arcfour256', 'arcfour128'] client mac:['hmac-sha2-256', 'hmac-sha1', 'hmac-sha1-96', 'hmac-md5'] server mac:['hmac-sha2-256', 'hmac-sha1', 'hmac-sha1-96', 'hmac-md5'] client compress:['none', 'zlib'] server compress:['none', 'zlib'] client lang:[''] server lang:[''] kex follows?False
paramiko.transport DEBUG - Ciphers agreed: local=aes256-ctr, remote=aes256-ctr
paramiko.transport DEBUG - using kex diffie-hellman-group1-sha1; server key type ssh-rsa; cipher: local aes256-ctr, remote aes256-ctr; mac: local hmac-sha1, remote hmac-sha1; compression: local none, remote none
paramiko.transport DEBUG - Switch to new keys ...
paramiko.transport DEBUG - Auth request (type=none) service=ssh-connection, username=test1
paramiko.transport INFO - Auth rejected (none).
paramiko.transport DEBUG - Auth request (type=publickey) service=ssh-connection, username=test1
pysshrpd.client INFO - 10.0.2.2:56011: trying publickey authentication for "test1"
paramiko.transport DEBUG - starting thread (client mode): 0x29752d0L
paramiko.transport INFO - Connected (version 2.0, client mod_sftp/0.9.8)
paramiko.transport DEBUG - kex algos:['diffie-hellman-group-exchange-sha256', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1', 'rsa1024-sha1'] server key:['ssh-rsa', 'ssh-dss'] client encrypt:['aes256-ctr', 'aes192-ctr', 'aes128-ctr', 'aes256-cbc', 'aes192-cbc', 'aes128-cbc', 'blowfish-ctr', 'blowfish-cbc', 'cast128-cbc', 'arcfour256', 'arcfour128', '3des-ctr', '3des-cbc'] server encrypt:['aes256-ctr', 'aes192-ctr', 'aes128-ctr', 'aes256-cbc', 'aes192-cbc', 'aes128-cbc', 'blowfish-ctr', 'blowfish-cbc', 'cast128-cbc', 'arcfour256', 'arcfour128', '3des-ctr', '3des-cbc'] client mac:['hmac-sha1', 'hmac-sha1-96', 'hmac-md5', 'hmac-md5-96', 'hmac-ripemd160'] server mac:['hmac-sha1', 'hmac-sha1-96', 'hmac-md5', 'hmac-md5-96', 'hmac-ripemd160'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
paramiko.transport DEBUG - Ciphers agreed: local=aes128-ctr, remote=aes128-ctr
paramiko.transport DEBUG - using kex diffie-hellman-group1-sha1; server key type ssh-rsa; cipher: local aes128-ctr, remote aes128-ctr; mac: local hmac-sha1, remote hmac-sha1; compression: local none, remote none
paramiko.transport DEBUG - Switch to new keys ...
paramiko.transport DEBUG - Adding ssh-rsa host key for 10.21.2.50: e074796aca334f65be4b19176752a04e
paramiko.transport DEBUG - Trying SSH key 1420cf7e0618a3365d5de6bc766066fa
paramiko.transport DEBUG - userauth is OK
paramiko.transport INFO - Authentication (publickey) successful!
paramiko.transport DEBUG - [chan 1] Max packet in: 34816 bytes
paramiko.transport DEBUG - [chan 1] Max packet out: 32768 bytes
paramiko.transport INFO - Secsh channel 1 opened.
pysshrpd.client INFO - 10.0.2.2:56011: connected to upstream test1@10.21.2.50:5022
paramiko.transport DEBUG - [chan 2] Max packet in: 34816 bytes
paramiko.transport DEBUG - [chan 2] Max packet out: 32768 bytes
paramiko.transport INFO - Secsh channel 2 opened.
paramiko.transport DEBUG - [chan 2] Sesch channel 2 request ok
paramiko.transport.sftp INFO - [chan 2] Opened sftp connection (server version 3)
paramiko.transport.sftp DEBUG - [chan 2] open('.ssh/authorized_keys', 'r')
paramiko.transport DEBUG - [chan 1] EOF sent (1)
paramiko.transport DEBUG - [chan 1] EOF received (1)
paramiko.transport DEBUG - EOF in transport thread
pysshrpd.client CRITICAL - 10.0.2.2:56011: authentication of "test1" with publickey failed
paramiko.transport INFO - Auth rejected (publickey).

FYI I run proftpd server on the upstream to provide sftp service, the authorized_keys file is defined by proftpd configure, looks like this is where the problem lies.

SFTPAuthorizedUserKeys file:/ftp-data/etc/authorized_keys/%u

**Comment by ybulach** [comment]
I just committed some changes to provide a new `upstream_authorized_keys` parameter, to change the default `.ssh/authorized_keys` file. Can you try pulling the last commit and adding:

```
"upstream_authorized_keys": "/ftp-data/etc/authorized_keys/test1",
```

in your upstream definition ?

**Comment by kevy1234** [comment]
@ybulach , thank you for the quick fix, it seems to be one step closer, but now I am getting new errors:

pysshrpd.client INFO - 10.0.2.2:57773: connected to upstream test1@10.21.2.50:5022
paramiko.transport DEBUG - [chan 2] Max packet in: 34816 bytes
paramiko.transport DEBUG - [chan 2] Max packet out: 32768 bytes
paramiko.transport INFO - Secsh channel 2 opened.
paramiko.transport DEBUG - [chan 2] Sesch channel 2 request ok
paramiko.transport.sftp INFO - [chan 2] Opened sftp connection (server version 3)
paramiko.transport.sftp DEBUG - [chan 2] open('/ftp-data/etc/authorized_keys/test1', 'r')
pysshrpd.client INFO - 10.0.2.2:57773: an error occurred while looking for the public key of "test1" in upstream's "/ftp-data/etc/authorized_keys/test1" file
pysshrpd.client DEBUG - Catched exception
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/pysshrp/clientthread.py", line 130, in check_auth_publickey
    with sftp.file(upstream.upstream_authorized_keys, 'r') as file:
  File "/usr/lib/python2.6/site-packages/paramiko/sftp_client.py", line 245, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "/usr/lib/python2.6/site-packages/paramiko/sftp_client.py", line 624, in _request
    return self._read_response(num)
  File "/usr/lib/python2.6/site-packages/paramiko/sftp_client.py", line 671, in _read_response
    self._convert_status(msg)
  File "/usr/lib/python2.6/site-packages/paramiko/sftp_client.py", line 697, in _convert_status
    raise IOError(errno.ENOENT, text)
IOError: [Errno 2] No such file
paramiko.transport DEBUG - [chan 1] EOF sent (1)
paramiko.transport DEBUG - EOF in transport thread
pysshrpd.client CRITICAL - 10.0.2.2:57773: authentication of "test1" with publickey failed
paramiko.transport INFO - Auth rejected (publickey).

Proftp uses RFC4716 key file format, it may need some sort of the conversion to base64.

**Comment by ybulach** [comment]
Pysshrp looks for the `authorized_keys` file through SFTP. The exception doesn't show format error for now, but:

```
IOError: [Errno 2] No such file
```

Is `/ftp-data/etc/authorized_keys/test1` readable via SFTP ?

Also, pysshrp will not be able to read RFC4716 for now, so even when the file will be readable, the lookup will not work. There will not be quick fixes for now, as Paramiko (that provides SSH/SFTP protocol to pysshrp) is only compatible with keys in the OpenSSH format.

Will your proftpd only be available via pysshrp ?
